const KEY='focus-planner-app-v3';
const defaults={category:'Lain-lain',priority:'medium',plan:'should',deadline:'',duration:30,start:'',subtasks:[]};
let todos=JSON.parse(localStorage.getItem(KEY)||'[]').map(t=>({...defaults,...t}));
let filter='all';
const $=s=>document.querySelector(s); const $$=s=>[...document.querySelectorAll(s)];
const priority={high:'🔴 Tinggi',medium:'🟡 Sederhana',low:'🟢 Rendah'}; const plans={must:'🔥 MUST DO',should:'⭐ SHOULD DO',could:'💡 COULD DO'};
const dur=m=>Number(m)>=60?`${Number(m)/60} jam`:`${m} min`;
const uid=()=>crypto.randomUUID?.()||`${Date.now()}-${Math.random()}`;
const save=()=>{localStorage.setItem(KEY,JSON.stringify(todos));render()};
const esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const deadline=v=>{if(!v)return'Tiada deadline';const d=new Date(v);return Number.isNaN(d.getTime())?'Tiada deadline':d.toLocaleString('ms-MY',{day:'2-digit',month:'short',hour:'2-digit',minute:'2-digit'})};
function add(text){if(!text.trim())return;todos.unshift({id:uid(),text:text.trim(),done:false,...defaults});save();$('#todoInput').value='';openEditor(todos[0].id)}
function openEditor(id){const t=todos.find(x=>x.id===id);if(!t)return;$('#editId').value=t.id;$('#editText').value=t.text;$('#editCategory').value=t.category;$('#editPriority').value=t.priority;$('#editDeadline').value=t.deadline;$('#editDuration').value=t.duration;$('#editStart').value=t.start;$('#editPlan').value=t.plan;$('#editSubtasks').value=(t.subtasks||[]).map(s=>s.text).join('\n');$('#editDialog').showModal()}
function visible(){return todos.filter(t=>filter==='all'||(filter==='active'&&!t.done)||(filter==='completed'&&t.done))}
function renderTasks(){const items=visible();$('#todoList').innerHTML=items.length?items.map(t=>`<article class="todo ${t.done?'done':''}"><button class="check" data-id="${t.id}" aria-label="Tanda selesai">${t.done?'✓':''}</button><div class="task-wrap"><div class="task">${esc(t.text)}</div><div class="meta"><span class="chip ${t.priority}">${priority[t.priority]}</span><span class="chip">${esc(t.category)}</span><span class="chip">${dur(t.duration)}</span><span class="chip">${deadline(t.deadline)}</span>${t.subtasks?.length?`<span class="chip">${t.subtasks.filter(s=>s.done).length}/${t.subtasks.length} subtugas</span>`:''}</div></div><button class="edit-button" data-edit="${t.id}">Edit</button><button class="delete" data-delete="${t.id}">×</button></article>`).join(''):'<div class="empty">Tiada tugasan dalam paparan ini.</div>'}
function renderTop(){const top=todos.filter(t=>!t.done).sort((a,b)=>({high:0,medium:1,low:2}[a.priority]-{high:0,medium:1,low:2}[b.priority])).slice(0,3);$('#topThree').innerHTML=top.length?top.map((t,i)=>`<div class="top-task"><div class="rank">${i+1}</div><div><strong>${esc(t.text)}</strong><small>${priority[t.priority]} · ${plans[t.plan]} · ${dur(t.duration)}</small></div></div>`).join(''):'<div class="empty">Semua tugasan selesai. 🎉</div>'}
function renderGroups(){['must','should','could'];$('#priorityGroups').innerHTML=['must','should','could'].map(p=>{const a=todos.filter(t=>t.plan===p&&!t.done);return `<div class="priority-group"><div class="group-title ${p}">${plans[p]} <span>(${a.length})</span></div>${a.slice(0,4).map(t=>`<div class="mini-task">• ${esc(t.text)}</div>`).join('')||'<div class="mini-task">Tiada tugasan.</div>'}</div>`}).join('')}
function renderSchedule(){const planned=todos.filter(t=>!t.done&&t.start).sort((a,b)=>a.start.localeCompare(b.start));const rows=planned.length?planned.map(t=>`<div class="slot"><div class="slot-time">${t.start}</div><div class="slot-name"><b>${esc(t.text)}</b><br><small>${dur(t.duration)} · ${priority[t.priority]}</small></div></div>`):[['08:00','MUST DO — kerja paling penting'],['10:00','Buffer + rehat'],['10:30','Sambung fokus'],['12:30','Makan tengah hari'],['14:00','SHOULD DO — komunikasi / urusan'],['15:30','Buffer + tugasan kecil'],['16:30','Daily wrap-up']].map((x,i)=>`<div class="slot ${[1,5].includes(i)?'buffer':''}"><div class="slot-time">${x[0]}</div><div class="slot-name">${x[1]}</div></div>`);$('#schedule').innerHTML=rows.join('')}
function renderReview(){const done=todos.filter(t=>t.done),pending=todos.filter(t=>!t.done),moved=pending.filter(t=>t.plan!=='must').slice(0,3);$('#reviewContent').innerHTML=[['✅ Selesai',done.map(t=>t.text)],['⏳ Belum selesai',pending.map(t=>t.text)],['➡️ Pindah ke esok',moved.map(t=>t.text)],['🏆 Pencapaian utama',[done.length?`Anda menyelesaikan ${done.length} tugasan.`:'Belum ada tugasan selesai.']]].map(([h,a])=>`<div class="review-block"><h3>${h}</h3><p>${a.length?a.map(esc).join(' · '):'Tiada.'}</p></div>`).join('')}
function render(){const done=todos.filter(t=>t.done).length,remaining=todos.length-done,pct=todos.length?Math.round(done/todos.length*100):0;$('#remaining').textContent=remaining;$('#completedCount').textContent=done;$('#mustCount').textContent=todos.filter(t=>!t.done&&t.plan==='must').length;$('#progressText').textContent=pct+'%';renderTop();renderGroups();renderTasks();renderSchedule();renderReview()}
function switchView(view){$$('.view').forEach(v=>v.classList.toggle('active-view',v.id===view));$$('.nav-item').forEach(b=>b.classList.toggle('active',b.dataset.view===view));window.scrollTo({top:0,behavior:'smooth'})}
$('#todoForm').addEventListener('submit',e=>{e.preventDefault();add($('#todoInput').value)});
$('#todoList').addEventListener('click',e=>{const id=e.target.dataset.id||e.target.dataset.edit||e.target.dataset.delete;if(!id)return;if(e.target.dataset.edit)openEditor(id);else if(e.target.dataset.delete){todos=todos.filter(t=>t.id!==id);save()}else{const t=todos.find(x=>x.id===id);if(t){t.done=!t.done;save()}}});
$$('.filter').forEach(b=>b.addEventListener('click',()=>{$$('.filter').forEach(x=>x.classList.remove('active'));b.classList.add('active');filter=b.dataset.filter;renderTasks()}));
$$('[data-view]').forEach(b=>b.addEventListener('click',()=>switchView(b.dataset.view)));
$('#clearCompleted').addEventListener('click',()=>{todos=todos.filter(t=>!t.done);save()});
$('#editForm').addEventListener('submit',e=>{e.preventDefault();const t=todos.find(x=>x.id===$('#editId').value);if(!t)return;Object.assign(t,{text:$('#editText').value.trim(),category:$('#editCategory').value,priority:$('#editPriority').value,deadline:$('#editDeadline').value,duration:Number($('#editDuration').value),start:$('#editStart').value,plan:$('#editPlan').value,subtasks:$('#editSubtasks').value.split('\n').map(x=>x.trim()).filter(Boolean).map(text=>({text,done:false}))});$('#editDialog').close();save()});
$('#closeDialog').addEventListener('click',()=>$('#editDialog').close());$('#deleteFromDialog').addEventListener('click',()=>{todos=todos.filter(t=>t.id!==$('#editId').value);$('#editDialog').close();save()});
const now=new Date();$('#dateText').textContent=now.toLocaleDateString('ms-MY',{weekday:'long',day:'numeric',month:'long',year:'numeric'});render();
let deferredPrompt;window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredPrompt=e;$('#installBtn').classList.remove('hidden')});$('#installBtn').addEventListener('click',async()=>{if(!deferredPrompt)return;deferredPrompt.prompt();deferredPrompt=null;$('#installBtn').classList.add('hidden')});
if('serviceWorker' in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('sw.js').catch(()=>{}));
