const KEY='focus-planner-v4';
const oldKey='focus-planner-app-v3';
const categories=['Personal','Work','Study','Shopping'];
const priorityRank={high:0,medium:1,low:2};
let tasks=JSON.parse(localStorage.getItem(KEY)||localStorage.getItem(oldKey)||'[]').map(t=>({id:t.id||crypto.randomUUID?.()||String(Date.now()+Math.random()),text:t.text||'',done:!!t.done,category:categories.includes(t.category)?t.category:'Personal',priority:t.priority||'medium',due:t.due||t.deadline?.slice?.(0,10)||'',time:t.time||t.start||''}));
let currentFilter='all', currentView='dashboard', search='';
let calendarDate=new Date(); let selectedDate=isoDate(new Date());
const $=s=>document.querySelector(s); const $$=s=>[...document.querySelectorAll(s)];
const esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
function isoDate(d){return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`}
function today(){return isoDate(new Date())}
function save(){localStorage.setItem(KEY,JSON.stringify(tasks));render()}
function formatDate(v){if(!v)return 'No date'; const d=new Date(v+'T00:00:00'); return d.toLocaleDateString('en-MY',{day:'numeric',month:'short'})}
function formatLong(v){const d=new Date(v+'T00:00:00');return d.toLocaleDateString('ms-MY',{weekday:'long',day:'numeric',month:'long',year:'numeric'})}
function dueLabel(t){if(!t.due)return 'No date'; let s=formatDate(t.due); if(t.time)s+=` · ${t.time}`; return s}
function isToday(t){return t.due===today() || (!t.due && !t.done)}
function isUpcoming(t){return !!t.due && t.due>today() && !t.done}
function openNew(){openEditor(null)}
function openEditor(id){const t=id?tasks.find(x=>x.id===id):null; $('#dialogTitle').textContent=t?'Edit Task':'New Task'; $('#taskId').value=t?.id||''; $('#taskText').value=t?.text||''; $('#taskCategory').value=t?.category||'Personal'; $('#taskPriority').value=t?.priority||'medium'; $('#taskDue').value=t?.due||''; $('#taskTime').value=t?.time||''; $('#deleteTask').classList.toggle('hidden',!t); $('#taskDialog').showModal(); setTimeout(()=>$('#taskText').focus(),50)}
function taskRow(t,withRank=false){return `<div class="task-row ${t.done?'done':''}"><button class="check ${t.done?'done':''}" data-check="${t.id}" aria-label="Mark task complete">${t.done?'✓':''}</button>${withRank?`<span class="rank">${withRank}</span>`:''}<div class="task-content"><div class="task-name">${esc(t.text)}</div><div class="task-meta"><span class="badge ${t.priority}">${t.priority[0].toUpperCase()+t.priority.slice(1)}</span><span class="badge">${esc(t.category)}</span><span class="badge">${dueLabel(t)}</span></div></div><div class="task-actions"><button class="small-btn" data-edit="${t.id}">Edit</button><button class="small-btn" data-delete="${t.id}" aria-label="Delete task">×</button></div></div>`}
function empty(text){return `<div class="empty">${text}</div>`}
function renderDashboard(){const total=tasks.length,done=tasks.filter(t=>t.done).length,pct=total?Math.round(done/total*100):0;$('#totalStat').textContent=total;$('#completedStat').textContent=done;$('#pendingStat').textContent=total-done;$('#highStat').textContent=tasks.filter(t=>!t.done&&t.priority==='high').length;$('#sidePending').textContent=total-done;$('#progressPercent').textContent=pct+'%';$('#progressBar').style.width=pct+'%';$('#progressLabel').textContent=`${done} of ${total} tasks completed`;
 const focus=tasks.filter(t=>!t.done&&(isToday(t)||t.priority==='high')).sort((a,b)=>priorityRank[a.priority]-priorityRank[b.priority]).slice(0,3); $('#focusList').innerHTML=focus.length?focus.map((t,i)=>`<div class="focus-item"><span class="rank">${i+1}</span><div class="task-content"><div class="task-name">${esc(t.text)}</div><div class="task-meta"><span class="badge ${t.priority}">${t.priority[0].toUpperCase()+t.priority.slice(1)} priority</span><span class="badge">${esc(t.category)}</span></div></div><button class="small-btn" data-edit="${t.id}">Edit</button></div>`).join(''):empty('Tiada fokus utama. Anda sudah ahead of schedule ✨');
 const recent=[...tasks].sort((a,b)=>Number(b.id?.includes('-')||0)-Number(a.id?.includes('-')||0)).slice(0,6); $('#recentList').innerHTML=recent.length?recent.map(t=>taskRow(t)):empty('Belum ada tugasan.');
 $('#categoryList').innerHTML=categories.map(c=>{const n=tasks.filter(t=>t.category===c).length;const max=Math.max(1,...categories.map(x=>tasks.filter(t=>t.category===x).length));return `<div class="category-row"><span class="category-name">${c}</span><div class="category-bar"><div style="width:${n/max*100}%"></div></div><span class="category-count">${n}</span></div>`}).join('')}
function filtered(){let arr=[...tasks]; if(currentFilter==='today')arr=arr.filter(isToday); if(currentFilter==='upcoming')arr=arr.filter(isUpcoming); if(currentFilter==='completed')arr=arr.filter(t=>t.done); if(search)arr=arr.filter(t=>(t.text+' '+t.category).toLowerCase().includes(search.toLowerCase())); return arr}
function renderLists(){const arr=filtered().sort((a,b)=>Number(a.done)-Number(b.done)); $('#allTaskList').innerHTML=arr.length?arr.map(t=>taskRow(t)).join(''):empty('No tasks match this view.'); const sets={today:tasks.filter(isToday),upcoming:tasks.filter(isUpcoming),completed:tasks.filter(t=>t.done)}; Object.entries(sets).forEach(([key,list])=>{const el=$(`#${key}List`); if(el)el.innerHTML=list.length?list.sort((a,b)=>Number(a.done)-Number(b.done)).map(t=>taskRow(t)).join(''):empty(key==='today'?'Nothing due today.':key==='upcoming'?'No upcoming tasks.':'No completed tasks yet.')})}
function renderCalendar(){const y=calendarDate.getFullYear(),m=calendarDate.getMonth(); $('#calendarMonth').textContent=new Date(y,m,1).toLocaleDateString('en-US',{month:'long'});$('#calendarYear').textContent=y; const first=new Date(y,m,1),start=(first.getDay()+6)%7,last=new Date(y,m+1,0).getDate(),prev=new Date(y,m,0).getDate(); let cells=''; for(let i=0;i<42;i++){let day=i-start+1,yy=y,mm=m;if(day<1){day=prev+day;mm=m-1;if(mm<0){mm=11;yy--}}else if(day>last){day=day-last;mm=m+1;if(mm>11){mm=0;yy++}} const d=isoDate(new Date(yy,mm,day)),inMonth=mm===m,has=tasks.some(t=>t.due===d),cls=[!inMonth?'muted':'',d===today()?'today':'',d===selectedDate?'selected':''].filter(Boolean).join(' ');cells+=`<button class="calendar-day ${cls}" data-date="${d}">${day}${has?'<span class="dot"></span>':''}</button>`} $('#calendarGrid').innerHTML=cells; $('#calendarWeek').innerHTML=['Mon','Tue','Wed','Thu','Fri','Sat','Sun'].map(x=>`<div>${x}</div>`).join(''); $('#selectedDateTitle').textContent=formatLong(selectedDate); const list=tasks.filter(t=>t.due===selectedDate); $('#selectedDateTasks').innerHTML=list.length?list.map(t=>taskRow(t)).join(''):empty('No tasks for this date.'); renderMiniCalendar()}
function renderMiniCalendar(){const d=new Date();$('#miniMonth').textContent=d.toLocaleDateString('en-US',{month:'long'});$('#miniYear').textContent=d.getFullYear();$('#miniWeek').innerHTML=['M','T','W','T','F','S','S'].map(x=>`<div>${x}</div>`).join('');const y=d.getFullYear(),m=d.getMonth(),start=(new Date(y,m,1).getDay()+6)%7,last=new Date(y,m+1,0).getDate();let html='';for(let i=0;i<start;i++)html+='<button disabled></button>';for(let day=1;day<=last;day++){const date=isoDate(new Date(y,m,day));const cls=[date===today()?'today':'',date===selectedDate?'selected':'',tasks.some(t=>t.due===date)?'has-task':''].join(' ');html+=`<button class="${cls}" data-mini-date="${date}">${day}</button>`}$('#miniGrid').innerHTML=html}
function render(){const now=new Date();$('#todayText').textContent=now.toLocaleDateString('ms-MY',{weekday:'long',day:'numeric',month:'long',year:'numeric'});$('#todayHeading').textContent=`${tasks.filter(isToday).length} task(s) scheduled for ${formatDate(today())}.`;renderDashboard();renderLists();renderCalendar();$$('.tab').forEach(b=>b.classList.toggle('active',b.dataset.filter===currentFilter))}
function switchView(view){currentView=view;$$('.view').forEach(v=>v.classList.toggle('active-view',v.id===view));$$('.nav-link,.mobile-nav button').forEach(b=>b.classList.toggle('active',b.dataset.view===view));window.scrollTo({top:0,behavior:'smooth'});if(view==='today')currentFilter='today';if(view==='upcoming')currentFilter='upcoming';if(view==='completed')currentFilter='completed';if(view==='tasks'&&['today','upcoming','completed'].includes(currentFilter))currentFilter='all';renderLists()}
function toggleTheme(){const dark=document.documentElement.dataset.theme==='dark';document.documentElement.dataset.theme=dark?'':'dark';localStorage.setItem('focus-theme',dark?'light':'dark');$('#themeLabel').textContent=dark?'Dark mode':'Light mode'}
$('#quickForm').addEventListener('submit',e=>{e.preventDefault();const v=$('#quickInput').value.trim();if(!v)return;tasks.unshift({id:crypto.randomUUID?.()||String(Date.now()),text:v,done:false,category:'Personal',priority:'medium',due:today(),time:''});$('#quickInput').value='';save()});
$('#heroAdd').onclick=$('#taskAdd').onclick=openNew; $$('[data-action="add"]').forEach(b=>b.onclick=openNew); $('#closeDialog').onclick=$('#cancelDialog').onclick=()=>$('#taskDialog').close();
$('#taskForm').addEventListener('submit',e=>{e.preventDefault();const id=$('#taskId').value;const data={text:$('#taskText').value.trim(),category:$('#taskCategory').value,priority:$('#taskPriority').value,due:$('#taskDue').value,time:$('#taskTime').value};if(!data.text)return;if(id){const t=tasks.find(x=>x.id===id);Object.assign(t,data)}else tasks.unshift({id:crypto.randomUUID?.()||String(Date.now()),done:false,...data});$('#taskDialog').close();save()});
$('#deleteTask').onclick=()=>{const id=$('#taskId').value;tasks=tasks.filter(t=>t.id!==id);$('#taskDialog').close();save()};
function delegated(e){const check=e.target.closest('[data-check]'),edit=e.target.closest('[data-edit]'),del=e.target.closest('[data-delete]');if(check){const t=tasks.find(x=>x.id===check.dataset.check);if(t)t.done=!t.done;save()}else if(edit)openEditor(edit.dataset.edit);else if(del){tasks=tasks.filter(x=>x.id!==del.dataset.delete);save()}}
document.addEventListener('click',e=>{delegated(e);const view=e.target.closest('[data-view]');if(view)switchView(view.dataset.view);const tab=e.target.closest('[data-filter]');if(tab){currentFilter=tab.dataset.filter;renderLists()}const day=e.target.closest('[data-date]');if(day){selectedDate=day.dataset.date;renderCalendar()}const mini=e.target.closest('[data-mini-date]');if(mini){selectedDate=mini.dataset.miniDate;calendarDate=new Date(selectedDate+'T00:00:00');switchView('calendar');render()} });
$('#searchInput').addEventListener('input',e=>{search=e.target.value;renderLists()});$('#prevMonth').onclick=()=>{calendarDate.setMonth(calendarDate.getMonth()-1);renderCalendar()};$('#nextMonth').onclick=()=>{calendarDate.setMonth(calendarDate.getMonth()+1);renderCalendar()};$('#themeToggle').onclick=toggleTheme;$('#mobileTheme').onclick=toggleTheme;
const savedTheme=localStorage.getItem('focus-theme');if(savedTheme==='dark')document.documentElement.dataset.theme='dark';$('#themeLabel').textContent=savedTheme==='dark'?'Light mode':'Dark mode';
let deferredPrompt;window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredPrompt=e;$('#installBtn').classList.remove('hidden')});$('#installBtn').onclick=async()=>{if(!deferredPrompt)return;deferredPrompt.prompt();deferredPrompt=null;$('#installBtn').classList.add('hidden')};
if('serviceWorker' in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('sw.js').catch(()=>{}));
render();
