const KEY='focus-todos-v1';let todos=JSON.parse(localStorage.getItem(KEY)||'[]');let filter='all';
const $=s=>document.querySelector(s);const input=$('#todoInput');const list=$('#todoList');
function save(){localStorage.setItem(KEY,JSON.stringify(todos));render()}
function add(text){text=text.trim();if(!text)return;todos.unshift({id:crypto.randomUUID(),text,done:false});save();input.value='';input.focus()}
function visible(){return todos.filter(t=>filter==='all'||(filter==='active'&&!t.done)||(filter==='completed'&&t.done))}
function render(){const items=visible();list.innerHTML=items.length?items.map(t=>`<article class="todo ${t.done?'done':''}"><button class="check" data-id="${t.id}" aria-label="Mark ${t.done?'active':'complete'}"></button><div class="task">${escapeHtml(t.text)}</div><button class="delete" data-delete="${t.id}" aria-label="Delete task">×</button></article>`).join(''):`<div class="empty">${filter==='completed'?'No completed tasks yet.':'Nothing here — add your first task above.'}</div>`;const remaining=todos.filter(t=>!t.done).length;$('#remaining').textContent=remaining;const done=todos.filter(t=>t.done).length;const pct=todos.length?Math.round(done/todos.length*100):0;$('#progressText').textContent=`${pct}% complete`;$('[id=progressBar]').style.width=pct+'%'}
function escapeHtml(s){return s.replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
$('#todoForm').addEventListener('submit',e=>{e.preventDefault();add(input.value)});list.addEventListener('click',e=>{const id=e.target.dataset.id||e.target.dataset.delete;if(!id)return;const t=todos.find(x=>x.id===id);if(e.target.dataset.delete){todos=todos.filter(x=>x.id!==id)}else if(t){t.done=!t.done}save()});document.querySelectorAll('.filter').forEach(b=>b.addEventListener('click',()=>{document.querySelector('.filter.active').classList.remove('active');b.classList.add('active');filter=b.dataset.filter;render()}));$('#clearCompleted').addEventListener('click',()=>{todos=todos.filter(t=>!t.done);save()});
const now=new Date();$('#dayName').textContent=now.toLocaleDateString(undefined,{weekday:'long'}).toUpperCase();$('#today').textContent=now.toLocaleDateString(undefined,{day:'2-digit',month:'short'}).toUpperCase();render();
